#!/usr/bin/env python
# encoding: utf-8
"""
slidescript.py - Slidescript paser and Converter

Created by Maximillian Dornseif on 2010-02-28.
Copyright (c) 2010 HUDORA. All rights reserved.
"""

from odict import odict
from slidescript.SlidescriptParser import *
from slidescript.antlr3 import *
from slidescript.antlr3.tree import *
from slidescript import SlidescriptLexer
import argparse
import os.path
import sys
import xlwt

# The internal code representation is the "namespace". Namespace is a dict
# where the key are variable names and the value is a node.
#
# A node can be one of the following:
#
# * `Variable` being a symbolic representation of something else. A
#   Variable points into the namespace. A Variable is always represented
#   as a string with a length greater than 1
# * `Operator` representing a mathematical operation. A Operator is always
#   represented as a string of length 1.
# * `Value` representing a numeric value. A Float is always represented
#   by a float value
# * `subtree` collecting other nodes. A subtreee usually starts with a
#   operater and is vollowed by Values or Variables. A Subtree is represented
#   by a tuple


def is_variable(node):
    return (isinstance(node, basestring) and len(node) > 1)


def is_unknown(node):
    return (isinstance(node, basestring) and node.startswith('?'))


def is_operator(node):
    return (isinstance(node, basestring) and len(node) == 1)


def is_value(node):
    return isinstance(node, float)


def is_subtree(node):
    return isinstance(node, tuple)


def node_to_string(node, var2loc={}, varprefix='', varpostfix=''):
    """Convert a node and it's subnodes to a string."""
    if is_variable(node):
        return '%s%s%s' % (varprefix, var2loc.get(node, node), varpostfix)
    elif is_value(node):
        return node
    elif is_subtree(node) and len(node) == 3 and is_operator(node[0]):
        return "(%s %s %s)" % (node_to_string(node[1], var2loc, varprefix, varpostfix),
                               node[0],
                               node_to_string(node[2], var2loc, varprefix, varpostfix))
    else:
        raise ValueError("unknown node type %r" % node)


def resolve_antlr_node(node, namespace):
    if node.getType() == VARIABLE:
        if node.getText() not in namespace:
            namespace[node.getText()] = '?Unknown'
        return node.getText()
    if node.getType() == CONSTANT:
        return float(node.getText())
    else:
        operation = node
        operand1 = node.getChild(0)
        operand2 = node.getChild(1)
        return (str(operation.getText()), resolve_antlr_node(operand1, namespace), resolve_antlr_node(operand2, namespace))


def node_to_string(node, var2loc={}, varprefix='', varpostfix=''):
    """Convert a node and it's subnodes to a string."""
    if is_variable(node):
        return '%s%s%s' % (varprefix, var2loc.get(node, node), varpostfix)
    elif is_value(node):
        return node
    elif is_subtree(node) and len(node) == 3 and is_operator(node[0]):
        return "(%s %s %s)" % (node_to_string(node[1], var2loc, varprefix, varpostfix),
                               node[0],
                               node_to_string(node[2], var2loc, varprefix, varpostfix))
    else:
        raise ValueError("unknown node type %r" % node)


def node_to_tex(node, var2loc={}, varprefix='', varpostfix=''):
    """Convert a node and it's subnodes to a string."""
    if is_variable(node):
        return '%s%s%s' % (varprefix, var2loc.get(node, node), varpostfix)
    elif is_value(node):
        return node
    elif is_subtree(node) and len(node) == 3 and is_operator(node[0]):
        if node[0] == '/':
            return "\\frac{%s}{%s}" % (node_to_tex(node[1], var2loc, varprefix, varpostfix),
                                       node_to_tex(node[2], var2loc, varprefix, varpostfix))
        elif node[0] == '*':
            return "%s \\times %s" % (node_to_tex(node[1], var2loc, varprefix, varpostfix),
                                      node_to_tex(node[2], var2loc, varprefix, varpostfix))
        else:
            return "%s %s %s" % (node_to_tex(node[1], var2loc, varprefix, varpostfix),
                                 node[0],
                                 node_to_tex(node[2], var2loc, varprefix, varpostfix))
    else:
        raise ValueError("unknown node type %r" % node)


def parse(value, debug=False):
    namespace = odict()
    char_stream = ANTLRStringStream(value+'\n')
    lexer = SlidescriptLexer.SlidescriptLexer(char_stream)
    tokens = CommonTokenStream(lexer)
    parser = SlidescriptParser(tokens)
    result = parser.program()
    # unser Root-Node heisst code und da haengen die enzelnen statements dran
    if result.tree.getType() != CODE:
        print result.tree.toStringTree()
        raise ValueError('invalid type %s' % result.tree.getType())
    statements = [result.tree.getChild(x) for x in range(result.tree.getChildCount())]
    for statement in statements:
        if debug:
            print statement.toStringTree()
        if statement.getChildCount() != 2:
            if not statement.token:
                continue
            raise ValueError(statement.toStringTree())
        var = statement.getChild(0)
        assert var.getType() == VARIABLE
        varname = var.getText()
        val = statement.getChild(1)
        assert var.getType() == VARIABLE
        namespace[varname] = resolve_antlr_node(val, namespace)
    return namespace


def calculate_dependencies_helper(node):
    ret = []
    if is_variable(node):
        ret.append(node)
    if is_subtree(node):
        for subnode in node:
            ret.extend(calculate_dependencies_helper(subnode))
    return ret


def calculate_dependencies(namespace):
    ret = odict()
    for varname in namespace:
        ret[varname] = calculate_dependencies_helper(namespace[varname])
    return ret


def ersetzen_helper(node, myvars):
    ret = []
    if is_variable(node) and is_value(myvars.get(node)):
        ret.append(myvars[node])
    elif is_subtree(node):
        for subnode in node:
            ret.append(ersetzen_helper(subnode, myvars))
    else:
        ret.append(node)
    if len(ret) > 1:
        return tuple(ret)
    return ret[0]


def ersetzen(namespace):
    """Ersetzt Variablen durch ihre Werte - wo möglich"""
    newnamespace = odict()
    for varname in namespace:
        newnamespace[varname] = ersetzen_helper(namespace[varname], namespace)
    if newnamespace != namespace:
        return ersetzen(newnamespace)
    return newnamespace


def berechnenen_helper(node, namespace):
    if is_subtree(node):
        if len(node) == 3 and is_operator(node[0]) and is_value(node[1]) and is_value(node[2]):
            operator = node[0]
            operand1 = node[1]
            operand2 = node[2]
            if operator == '+':
                return operand1 + operand2
            if operator == '-':
                return operand1 - operand2
            if operator == '*':
                return operand1 * operand2
            if operator == '/':
                return operand1 / operand2
        else:
            ret = []
            for subnode in node:
                ret.append(berechnenen_helper(subnode, namespace))
            return tuple(ret)
    return node


def berechnenen(namespace):
    newnamespace = odict()
    for varname in namespace:
        newnamespace[varname] = berechnenen_helper(namespace[varname], namespace)
    return newnamespace


def solver(namespace):
    """Werte auflösen, bis alles klärbare geklärt ist."""
    newnamespace = berechnenen(ersetzen(namespace))
    if namespace == newnamespace:
        return namespace
    return solver(newnamespace)


def generate_dotfile(namespace, outfd):
    """Generate a graphviz DOT file displaying the Variable dependencies."""
    outfd.write('# autogenerated from %s - do not edit\n' % outfd.name)
    outfd.write('digraph graphname {\n')
    # see http://www.graphviz.org/cvs/doc/info/attrs.html#d:ratio
    # and http://www.graphviz.org/cvs/doc/info/attrs.html#d:size
    outfd.write('    graph [ratio="compress", size="8.25,11.75"]\n')
    #outfd.write('    graph [ratio="0.7", size="8.25,11.75"]\n')
    for varname, dependencies in calculate_dependencies(namespace).items():
        for dependenciy in dependencies:
            outfd.write('    "%s" -> "%s";\n' % (dependenciy, varname))
    outfd.write('}\n')


def generate_resolvedfile(namespace, outfd):
    """Generates a file conainin resolved variables."""
    for varname, value in solver(namespace).items():
        outfd.write('    %s = %s\n' % (varname, value))


def generate_xlsfile(namespace, outfd):
    """Excel Sheet mit allen Formeln generieren."""
    wb = xlwt.Workbook()
    ws = wb.add_sheet(("Slidescript %s" % outfd.name).replace('/', '_')[:31])
    # Set to landscape
    ws.portrait = 0
    # Style für Felder, die von And belegt werden müssen
    style_unknown = xlwt.XFStyle()
    style_unknown.pattern = xlwt.Pattern()
    style_unknown.pattern.pattern = xlwt.Pattern.SOLID_PATTERN
    style_unknown.pattern.pattern_fore_colour = 5 # (YELLOW)
    var2loc = {} # wo schreiben wir die Variablen hin
    row = 1
    ws.write(0, 0, 'Variable')
    ws.write(0, 1, 'Wert')
    ws.write(0, 2, 'Beschreibung')

    for varname, value in namespace.items():
        ws.write(row, 0, varname)
        # Note where the Value of the Variable will be ($A$1)
        if is_subtree(value):
            # Beschreibung der Formel
            ws.write(row, 2, node_to_string(value))
        row += 1
        # My understanding o Excel seems to have a off by one Error.
        var2loc[varname] = "B%s" % (row)
        # oder lieber relativ?
        # var2loc[varname] = "$B$%s" % (row)

    # Formeln schreiben mit ersetzten Variablen
    row = 1
    for varname, value in namespace.items():
        if is_unknown(value):
            # unknown var
            ws.write(row, 1, '', style_unknown)
        else:
            ws.write(row, 1, xlwt.Formula("%s" % node_to_string(value, var2loc)))
        row += 1

    # Save the workbook
    wb.save(outfd)


def generate_jsfile_helper(namespace, outfd, already_written):
    written_something = False
    for varname, dependencies in calculate_dependencies(namespace).items():
        if varname in already_written:
            continue
        # wenn alle dependencies für die Variable schon geschrieben sind,
        # schreiben wir auch die Variable
        if [x for x in dependencies if (x not in already_written)] == []:
            # alle Abhängigkeiten sind schon geschrieben
            already_written.add(varname)
            outfd.write("    // %s\n" % (varname))
            outfd.write("    writeVar('%s', %s);\n" % (varname, node_to_string(namespace[varname], varprefix="readVar('", varpostfix="')")))
            written_something = True
    if written_something:
        return generate_jsfile_helper(namespace, outfd, already_written)
    return already_written


def generate_jsfile(namespace, outfd):
    already_written = set() # liste der bereits verarbeiteten Variablen
    # zunächst die Variablen, die von nichts anderen Abhängen

    outfd.write("""// autogenerated to %s - do not edit
function writeVar(varname, value) { // write data into value or text (innerHTML)
    $('.sv#' + varname).val(value);
    $('.sv#' + varname).text(value);
};
function initSlidescriptFields() {
""" % outfd.name)
    for varname, dependencies in calculate_dependencies(namespace).items():
        if not dependencies:
            already_written.add(varname)
            outfd.write("    writeVar('%s', %s);\n" % (varname, namespace[varname]))

    outfd.write("    updateSlidescriptFields();\n")
    outfd.write("    updatefunc = function() { updateSlidescriptFields() };")
    outfd.write("    $('.sv').blur(updatefunc).submit(updatefunc);\n")
    outfd.write("};\n")
    outfd.write("""

function updateSlidescriptFields() {
    function readVar(varname) { // read value for input fields or content from childs
        return (parseFloat($('.sv#' + varname).val() || $('.sv#' + varname).text()));
    };
""")

    already_written = generate_jsfile_helper(namespace, outfd, already_written)
    outfd.write("};\n")


def generate_htmlfile(namespace, outfd):
    outfd.write("""
<html>
  <head>
    <title>Slidescript %(basename)s</title>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.js"></script>
    <script type="text/javascript" src="%(basename)s.js"></script>
    <script type="text/javascript">
    $(document).ready(function() {
        // Code, der beim Laden der Seite ausgefuehrt wird
        initSlidescriptFields()
    });
    </script>
  </head>
  <body>
  <form action="javascript:void(0);" class="sv">
""" % {'basename': os.path.basename(os.path.splitext(outfd.name)[0])})
    for varname, value in namespace.items():
        outfd.write('      <div class="%s">\n' % (varname))
        outfd.write('        <label for="%s">%s</label>\n' % (varname, varname))
        if is_value(value):
            outfd.write('        <input type="text" id="%s" class="sv" autocomplete="off" title="%s">\n' % (varname, node_to_string(value)))
        else:
            outfd.write('        <input type="text" id="%s" class="sv" READONLY title="%s">\n' % (varname, node_to_string(value)))
        outfd.write('      </div>\n')
    outfd.write('      <input type="submit">\n')
    outfd.write('    </form>\n')
    outfd.write("  </body>\n</html>")


def generate_pyfile_helper(namespace, outfd, already_written):
    written_something = False
    for varname, dependencies in calculate_dependencies(namespace).items():
        if varname in already_written:
            continue
        # wenn alle dependencies für die Variable schon geschrieben sind,
        # schreiben wir auch die Variable
        if [x for x in dependencies if (x not in already_written)] == []:
            # alle Abhängigkeiten sind schon geschrieben
            already_written.add(varname)
            outfd.write("    // %s\n" % (varname))
            outfd.write("    writeVar('%s', %s);\n" % (varname, node_to_string(namespace[varname], varprefix="readVar('", varpostfix="')")))
            written_something = True
    if written_something:
        return generate_jsfile_helper(namespace, outfd, already_written)
    return already_written


def generate_pyfile(namespace, outfd):
    already_written = set() # liste der bereits verarbeiteten Variablen
    outfd.write("""# autogenerated to %s - do not edit
class Slisescript(object):
    def __init__(self, **kwargs):
""" % outfd.name)
    # Statische Werte werden als Klassenvariablen geschrieben
    for varname, dependencies in calculate_dependencies(namespace).items():
        if not dependencies:
            already_written.add(varname)
            outfd.write("        self.%s = %s\n" % (varname, namespace[varname]))
    outfd.write("        for name, value in kwargs.items():\n")
    outfd.write("            setattr(self, name, value)\n")

    for varname, dependencies in calculate_dependencies(namespace).items():
        if varname in already_written:
            continue
        already_written.add(varname)
        outfd.write("\n    @property\n")
        outfd.write("    def %s(self):\n" % (varname))
        outfd.write("        return(%s)\n" % (node_to_string(namespace[varname], varprefix="self.")))
    return already_written


def generate_texfile(inputcode, namespace, outfd):
    already_written = set() # liste der bereits verarbeiteten Variablen
    outfd.write("""%%  %s - autogenerated - do not edit
\\documentclass[a4]{article}
%%\\documentclass[landscape,a4]{article}
\\usepackage[utf8x]{inputenc}
%%\\usepackage[landscape,pdftex]{geometry}
\\begin{document}
""" % outfd.name)

    for line in inputcode:
        if not line.startswith('    '):
            if line.startswith('#'):
                if line.startswith('###'):
                    line = '\\subsubsection{%s}' % line.strip('# ')
                elif line.startswith('##'):
                    line = '\\subsection{%s}' % line.strip('# ')
                else:
                    line = '\\section{%s}' % line.strip('# ')
                outfd.write(line.encode('utf-8'))
            else:
                outfd.write(line.encode('utf-8'))
        else:
            line = line.strip().replace('=', ' ')
            varname = line.split(' ')[0]
            print varname
            if varname not in namespace:
                pass
            elif namespace[varname] == '?Unknown':
                pass
            else:
                outfd.write("\\begin{equation}\n")
                outfd.write("    %s = %s\n" % (varname, node_to_tex(namespace[varname])))
                outfd.write("\\end{equation}\n")
    # outfd.write("\\begin{displaymath}%s = %s\\end{displaymath}\n" % (varname, namespace[varname]))
    outfd.write("\n")
    outfd.write("\\end{document}\n")


# create the parser
parser = argparse.ArgumentParser(
    description='Parse and convert Slidescript')
#parser.add_argument('infile', nargs='?', help='y help', default=sys.stdout)
parser.add_argument('infile', nargs='?', type=argparse.FileType('r'), const=sys.stdin,
    help='Programmcode zum einlesen, wenn nicht angegeben, wird von stdin gelesen.')
parser.add_argument('-dC', '--debug-preprocessor', action='store_true', help='debug input proprocessing')
parser.add_argument('-dP', '--debug-parser', action='store_true', help='debug input parsing')
parser.add_argument('-dD', '--debug-dependencies', action='store_true', help='debug variable dependencies')
parser.add_argument(
    '--dot', nargs='?', type=argparse.FileType('w'), const=sys.stdout,
    help='write a Graphviz/dot file displaying the Variable-dependencies')
parser.add_argument(
    '--resolved', nargs='?', type=argparse.FileType('w'), const=sys.stdout,
    help='write a text file with the resolved Variables')
parser.add_argument(
    '--xls', nargs='?', type=argparse.FileType('w'), const=sys.stdout,
    help='compile to XLS')
parser.add_argument(
    '--js', nargs='?', type=argparse.FileType('w'), const=sys.stdout,
    help='compile to Javascript')
parser.add_argument(
    '--html', nargs='?', type=argparse.FileType('w'), const=sys.stdout,
    help='build HTML to use Javascript')
parser.add_argument(
    '--py', nargs='?', type=argparse.FileType('w'), const=sys.stdout,
    help='compile to Python')
parser.add_argument(
    '--tex', nargs='?', type=argparse.FileType('w'), const=sys.stdout,
    help='compile to LaTeX')

# parse the command line
args = parser.parse_args()

sourcelines = []
inputcode = []
for line in  args.infile.readlines():
    line = line.decode('utf-8')
    inputcode.append(line)
    if line.startswith('    '):
        sourcelines.append(line.strip())
    else:
        sourcelines.append(' ') # to keep line count constant

sourcecode = ('\n'.join(sourcelines)) + '\n'
namespace = parse(sourcecode, args.debug_parser)

if args.debug_preprocessor:
    print "-" * 50
    print sourcecode
    print "-" * 50    
if args.debug_dependencies:
    for varname, dependencies in calculate_dependencies(namespace).items():
        print ("%s -> %s" % (varname, dependencies))


if args.dot:
    generate_dotfile(namespace, args.dot)
if args.resolved:
    generate_resolvedfile(namespace, args.resolved)
if args.xls:
    generate_xlsfile(namespace, args.xls)
if args.js:
    generate_jsfile(namespace, args.js)
if args.html:
    generate_htmlfile(namespace, args.html)
if args.py:
    generate_pyfile(namespace, args.py)
if args.tex:
    generate_texfile(inputcode, namespace, args.tex)
